version: '3.3'
services:
  mariadb:
    build: .
    image: ragedunicorn/mariadb:1.0.0-stable
    volumes:
      - mariadb_data:/var/lib/mysql
    expose:
      - "3306"
    labels:
      com.ragedunicorn.mariadb.environment: "prod"
      com.ragedunicorn.mariadb.description: "MariaDB"
volumes:
  mariadb_data: {}
