version: '3.6'
services:
  mariadb:
    build: .
    image: ragedunicorn/mariadb:${MARIADB_TAG_VERSION}-stable
    volumes:
      - mariadb_data:/var/lib/mysql
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1m
      timeout: 10s
      retries: 3
    labels:
      com.ragedunicorn.mariadb.environment: "prod"
      com.ragedunicorn.mariadb.description: "MariaDB"
volumes:
  mariadb_data: {}
