version: '3.8'
services:
  mariadb:
    build: .
    image: ragedunicorn/mariadb:${MARIADB_TAG_VERSION}-dev
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
    labels:
      com.ragedunicorn.mariadb.environment: "dev"
      com.ragedunicorn.mariadb.description: "MariaDB"
volumes:
  mariadb_data: {}
