version: '3.7'
services:
  mariadb:
    image: ragedunicorn/mariadb:1.1.1-stable
    volumes:
      - mariadb_data:/var/lib/mysql
    secrets:
      - com.ragedunicorn.mariadb.root_password
      - com.ragedunicorn.mariadb.app_user
      - com.ragedunicorn.mariadb.app_user_password
    healthcheck:
      test: ["CMD", "/docker-healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    labels:
      com.ragedunicorn.mariadb.environment: "prod"
      com.ragedunicorn.mariadb.description: "MariaDB"
volumes:
  mariadb_data: {}
secrets:
  com.ragedunicorn.mariadb.root_password:
    external: true
  com.ragedunicorn.mariadb.app_user:
    external: true
  com.ragedunicorn.mariadb.app_user_password:
    external: true
